### ISSUE TITLE
Pause did not work

### ISSUE THREAD

**Issue by Leo-MapCreator** [haxball/haxball-issues#286] opened 2018-05-18 19:31 UTC
Admin paused the game but it didnt pause, it showed on the chat that the admin had paused but it didnt pause in fact

**Comment by basro** [comment] 2018-05-18 22:17
With this little info I can't begin finding the cause of the bug, if you find a way to reproduce it or perhaps record it in a haxball replay it would be useful.

**Comment by Leo-MapCreator** [comment] 2018-05-18 23:51
i dont have any information either, it was totally random, idk, maybe he lagged when he pressed pause and it only sent the chat message, to solve this i think its better to look in the code to find a way for this to happen

**Comment by Leo-MapCreator** [comment] 2018-05-18 23:51
When he pressed the second time it worked, it didnt work just the first time

**Comment by Wrathen** [comment] 2018-05-19 00:16
It's like saying "I have an ache" to your doctor without any other information. Doctor can't do anything about it. You need to provide some symptoms.
Like even the information of "Was the admin a host or a player?" may matter.

**Comment by Wrathen** [comment] 2018-05-19 00:27
You tell him when the pain started, where is it. What does it feel like. How often it occurs. etc :D You tell actually a lot

**Comment by Leo-MapCreator** [comment] 2018-05-19 00:47
Admin paused the game but it didnt pause, it showed on the chat that the admin had paused but it didnt pause in fact.
I dont have any information either, it was totally random, idk, maybe he lagged when he pressed pause and it only sent the chat message, to solve this i think its better to look in the code to find a way for this to happen.
When he pressed the second time it worked, it didnt work just the first time.

**Comment by Wrathen** [comment] 2018-05-19 00:51
Maybe you lagged? :D

**Comment by basro** [comment] 2018-05-19 00:51
Ok well, I looked a bit at the source and I found a way in which this could happen :P

I'll be marking it as a bug and fixing it eventually but this is a really benign bug that wont really bother anyone.

**Comment by Wrathen** [comment] 2018-05-19 00:52
Basro what about the headless thing :c

**Comment by basro** [comment] 2018-05-19 00:54
Wrathen, this is not a forum, don't post about things unrelated to the issue.
I haven't forgotten about it, I will do it eventually so have patience please.

**Comment by Leo-MapCreator** [comment] 2018-05-19 00:55
Totally unrelated to the issue, but related to your comment, will haxball have a forum? @basro

**Comment by Wrathen** [comment] 2018-05-19 00:55
room.sendChat("me sad, me no power :(");

**Comment by basro** [comment] 2018-06-05 23:13
This should be fixed now.

**Closed by basro** 2018-06-05 23:13 UTC
Labels: bug
