### ISSUE TITLE
Master Connection Error - Server Downtime 06/02/2019

### ISSUE THREAD

**Issue by killmeplease11** [haxball/haxball-issues#693] opened 2019-02-06 19:50 UTC
Hi, this is my first time that i write in this site. 

Well, there is this issue since 30 minutes (i think), all players every time that have to join in some rooms, they get the warn ''Master Connection Error'', i hope you can fix asap. 

Ty ♥

**Comment by basro** [comment] 2019-02-06 21:41
It seems to be running now, I happened to see the all the reports just as the server had come back online so I am unsure of what the cause was. I'll remain on alert to be able to debug it if it happens again today.

If the server continues to run fine I'll close this issue tomorrow.

**Comment by basro** [comment] 2019-02-06 21:43
It seems to be running now, the issues were probably caused by downtime of
the service providers I use for the site. I'll remain alert.

**Comment by killmeplease11** [comment] 2019-02-06 22:59
@basro thanks ♥

**Closed** 2019-02-07 19:46 UTC
