### ISSUE TITLE
Remembering the filters on room list

### ISSUE THREAD

**Issue by mtave** [haxball/haxball-issues#112] opened 2017-11-02 16:13 UTC
Well ye the filters always set back to default when you doing any action (join room, change nickname etc.). No big deal for sure but would be a little more comfortable if filters stays the same.

**Comment by helppe** [comment] 2017-11-02 18:43
https://github.com/haxball/haxball-issues/issues/23

**Comment by basro** [comment] 2017-11-03 13:01
Closing because it's a duplicate of #23

**Closed by basro** 2017-11-03 13:01 UTC
Labels: duplicate, enhancement
