### ISSUE TITLE
The room is full.

### ISSUE THREAD

**Issue by shaxlele** [haxball/haxball-issues#231] opened 2018-03-28 21:15 UTC
Hello, guys. As I play so much on HTML and I really like that, so, main problem for me is that when I want to join some room like 3v3 in balkan rooms, I see the slot, for example, 9/10, then I try to join the room, but it says that "The room is full.", then I ask my friends to give me slot and they still say there's still one slot, I tried to join the room, like 20 times, but it didn't help, maybe you can fix that.
I play Haxball on the laptop, so I hope you can fix that bug.

**Comment by shaxlele** [comment] 2018-03-28 21:16
In other rooms too, I don't know what's the problem, maybe it's bug on my laptop or?

**Comment by basro** [comment] 2018-03-28 21:18
This is a duplicate of issue #221
There's a workaround you can use explained in that thread.

**Closed by basro** 2018-03-28 21:18 UTC
Labels: duplicate
