### ISSUE TITLE
Transparent kits bug?

### ISSUE THREAD

**Issue by uzayyli** [haxball/haxball-issues#2119] opened 2024-02-22 22:12 UTC
Hi,

This issue just started today. Every room I join, I see transparent kits, players are only black circles with transparent filling. If I go to settings and toggle "enable custom team colors" two times, it seems to fix the issue.

After I the issue is "fixed", if a new player is added, they also join the game with a transparent kit.

I'm using Firefox on Windows 10, haven't tried on other browsers yet.

**Edit**: This doesn't happen on Debian Firefox ESR, only Windows and it started right after downloading the update for v123.0 so it's possible that Mozilla broke something. Looks like the game code wasn't updated recently?

**Comment by basro** [comment] 2024-02-23 00:06
I was able to reproduce, looks like a bug in FireFox 123. I'll see if I can find a workaround.

**Comment by uzayyli** [comment] 2024-02-23 01:58
Thank you basro! I also submitted a similar report to Mozilla. Hope they fix it :)

**Comment by basro** [comment] 2024-02-23 02:47
I was able to find a workaround, should be fixed now.

**Closed as completed by basro** 2024-02-23 02:47 UTC
Labels: bug

**Comment by uzayyli** [comment] 2024-02-23 04:07
It is fixed! Thanks again basro.
