### ISSUE TITLE
Arrow indicator of Player And Ball

### ISSUE THREAD

**Issue by Raamyy** [haxball/haxball-issues#52] opened 2017-10-26 20:50 UTC
Add arrow indicator for players who are out of screen view.
And also the Ball position

**Comment by BrazilHax** [comment] 2017-10-26 21:06
I also missed the arrows.

**Comment by Raamyy** [comment] 2017-10-26 22:00
@BrazilHax  Which Arrows ?

**Comment by basro** [comment] 2017-10-26 22:15
This is a duplicate of #38

**Closed by basro** 2017-10-26 22:15 UTC
Labels: duplicate, flash-feature
