### ISSUE TITLE
Country Changer + FPS Changer

### ISSUE THREAD

**Issue by Haxballing** [haxball/haxball-issues#150] opened 2017-11-11 11:59 UTC
Hello, I am pretty sure anyone needs now the very important things which called Country changer and FPS Changer.
Please make them in the new update version fast as possibole.
Add all the countries to a Change a country list like in the [Flash] version.
and try mabey this time make the FPS Changer make us to choose from 0-60 not only 30 or 60 like it was in the [Flash] version ok?
Please do it and answer me who with me and who want this too like me ! :+1:  :100: 
Please make this Haxball Team and answer me pls if this also can be possibole to make those things i want and i worte here.
Thanks for answers, Have a nice day !!!

**Comment by basro** [comment] 2017-11-11 12:01
Duplicate of #78 and #124

**Closed by basro** 2017-11-11 12:01 UTC

**Comment by Haxballing** [comment] 2017-11-11 12:06
Oh Sorry i didnt saw.
but i dont think someone suggest make the fps let us choose from 0-60 instead of only 60 or 30.

**Comment by Haxballing** [comment] 2017-11-11 12:08
Can u also maybe tell me if this can be those fueatures and when ?
Sorry for my bad english...

**Comment by slavel** [comment] 2017-11-11 14:47
+++
