### ISSUE TITLE
html5 VPS hosts

### ISSUE THREAD

**Issue by iscoman** [haxball/haxball-issues#242] opened 2018-04-24 09:13 UTC
Hi Basro, Feed-Me community has recently announced that they are going to move to HTML5 next season (don't know if you familiar with it, but FM is probably the biggest haxball community and the most competitive one), after testing it yesterday, we found a few bugs.
Since a few years ago many players have started to get VPS hosts, which made our experience in haxball much better, flash haxball was something else for players that are used to play abroad with 151 ping.
Playing with a VPS host on HTML5 is a bit different, pings are great ofc, but when there is a "spamming" situation there is an huge spike for everyone involved. Also, there are a few other ping bugs for some other players, (it happens on every vps host).
Also when we play on a regular hosts, pings seem to be much better than flash, but for players like me (which are from Israel, turkey etc) it a bit harder, we usually have around 90 ping on European hosts, the problem is that 90 ping on html5 really feels like 184 on flash, unfortunately  I know there is not much you can do about the fact that countries like Israel has bad ping on Europe.
Do you know anything about those VPS ping problems? 
Thank you for your time!

**Comment by basro** [comment] 2018-04-24 12:25
I don't know much about hosting haxball on VPSs. It's not exactly designed for it since it does a lot of work that is unnecesary in a headless host environment (rendering, sounds, etc)

I might be wrong but I believe some people have been hosting using VPSs successfully, in particular in poland and that spacebounce room. So maybe try contacting some of them about it.

Regarding the laggy experience with low ping: You should also be looking at the max ping and the ping graph, how high is it? how flat is the graph? Could you upload a screenshot of your usual ping graph?

**Comment by XHerna** [comment] 2018-04-24 14:38
Hi,
are you using another networking thing for predicting the players positions than in Flash?

The thing with the lag at lower ping isco is referring to is just that the game becomes unplayable when the player just lags a bit, because the own player jumps around a lot aswell and everything looks like constantly spiking, while on Flash you could play with ping up to 200 quite fine, because your own player moved correctly and the actions of other players were easily predictable for experienced players.

**Comment by humpyy** [comment] 2018-04-25 15:28
Does the host respond to player actions in increments smaller than 64 ms? 

If not, would it make sense if, by default, all users had a handicap of 64 applied?  

Anecdotally, I have players who have a solid ping of 30ms in my rooms, many under 64ms.  If I understand correctly, this means players with pings of 30ms-64ms would see jitter when ping bumps up from 79 to 100, which should be a good ping.

**Comment by basro** [comment] 2018-04-25 17:35
I guess I was not very clear, I'll make a better effort of explaining:

HaxBall has prediction, this means that the server sends you the state of the game and the game is fast forwarded to some time in the future.
How much in the future you play is calculated more or less like this: ping + handicap + noise_window
ping is the number displayed in the UI
handicap is whatever msecs you set to your handicap
noise_window is a fixed extra delay that is there to allow your messages some wiggle room above of ping.

Your messages take time to arrive at the host. If when they arrive it's already in the past then the server will correct you, which means if the message takes more than ping / 2 + handicap + noise_window to arrive at the host your player will warp around.
This is why I suggested using the handicap feature, since it's equivalent to giving yourself a bigger noise window (at the cost of playing further in the future making prediction more uncertain/warpy)

This works the same in both flash and html5, but there's a difference in how ping is calculated and the size of the noise_window.

In flash the ping is the 95th percentile of the last 100 ping samples, in html5 it's using the 50th percentile (the median).
In flash the noise_window is smaller, only 16ms, while in html5 it's 64.
This difference could negatively affect people who have very noisy ping, since the ping value will be lower in html5 than flash. But by using handicap you can make html5 behave the same as flash (by adding the extra ping that you are missing).

"why don't you make it use 95th percentile again then?"
Because the html5 way is better for everyone else who doesn't have really noisy ping. People with noisy ping can fix it manually by using handicap. That is if the cause really a uniformly noisy ping, which is why I wanted a screenshot of the ping graph, to be able to determine if that's actually what is going on.

I am considering increasing the noise_window from 64 to 96ms which could help a bit, can't increase it much more than that since there's other drawbacks to it.

Hope this helps

**Comment by basro** [comment] 2018-04-25 17:53
Also, I'm considering changing the ping displayed in the room lobby next to the nicks to be the max ping of the last 10 samples or something like that, since that information is more useful to know if a player is actually lagging.

**Comment by humpyy** [comment] 2018-04-26 15:39
Good insight and thanks for sharing.  I've advised the group to try a handicap if they're seeing jitter while having a low ping.

**Comment by basro** [comment] 2018-04-26 15:42
I'm closing this issue since it's not really one, but feel free to continue the conversation here.

**Closed by basro** 2018-04-26 15:42 UTC

**Comment by basro** [comment] 2018-05-12 02:28
I've released a headless version which is better suited to use on a VPS.
Try it [here](https://github.com/haxball/haxball-issues/wiki/Headless-Host)

**Comment by basro** [comment] 2018-05-19 23:40
I just realized that the handicap feature was actually quite bugged and not at all doing what I described in my post above in this thread. Oops..

This means: Bugged as it is it does not at all contribute towards the noise window and in fact it makes your own player *always* warp. So my advice, while it makes sense if the feature is working correctly, was pretty much useless...

I'll be fixing it soon, hopefully those who read this thread before get notified :P
