### ISSUE TITLE
Can't join some rooms

### ISSUE THREAD

**Issue by AlucarD2211** [haxball/haxball-issues#793] opened 2019-07-11 19:24 UTC
Hello,i have a problem.Yesterday i was playing all normally,today i tried to join in a room ''3v3 luck pro vps'' and it didn't works.Problem:Connection closed(1000).Can you help me?I can join in some rooms but some not..

**Comment by basro** [comment] 2019-07-11 19:29
This is a duplicate of #791.

I'll close this issue, please post any follow up in the other issue.

Are you using Chrome or Firefox? Please try disabling all browser extensions.

**Closed** 2019-07-11 19:29 UTC
