### ISSUE TITLE
Room disappears after a certain time

### ISSUE THREAD

**Issue by evi1a** [haxball/haxball-issues#652] opened 2018-12-16 00:56 UTC
I'm hosting a couple of rooms for quite a while and I usually don't need to restart them.
But since some days, the rooms disappear after a certain time from the list and if you try to join them using the link you get a `Connection closed (4001)` error.
I haven't touched the script for at least a month and I encounter this error on different machines from different hosters but there is no error message in the console.

**Comment by PiotrLew** [comment] 2018-12-16 12:07
hey, I have the same! since morning was throwing out the room 4 times. not just mine, all vps. room for api stands but he is thrown out by haxball. HELP ! Crash often occurs and throws out the whole haxball. you can see it on the menu because is written 10 rooms , 100 people  before it was 1000 people 70 rooms. FIX THIS

**Comment by evi1a** [comment] 2018-12-16 12:41
Sometimes it stays longer, sometimes less but it crashes within a day. Most of the times it's a couple of hours, but it also happened in less than an hour already. I would say since 2-3 days.

If you haven't changed anything at that part, it's weird that it doesn't show any WebRTC related error or actually any error in the room when that happens.

**Comment by basro** [comment] 2018-12-16 12:45
Does the recaptcha dialog appear when this happens?

It is indeed looking like a bug, I'll be trying to reproduce it.

**Comment by evi1a** [comment] 2018-12-16 12:54
I can't tell because of headless. Maybe Piotr can help there or I'll try to reproduce it on my local machine. But maybe it involves activity so Idk

**Comment by NiExTy** [comment] 2018-12-16 12:56
I reported exact same problem 3 weeks ago #633.

My last room stayed up for a 5 days before I had to restart it.

> Does the recaptcha dialog appear/reset when this happens?

Not for me, I used tokens (if that matters).

**Comment by basro** [comment] 2018-12-16 13:18
@NiExTy, I apologize for taking this long to take action. I've been busy lately and I didn't understand how wide spread this issue was so I didn't give it the proper priority.

> Sometimes Haxball goes down and throws Cloudflare errors for a while. Which can cause headless to lose connection (?). Haxball thinks connection closed, token expires. Room can't reappear anymore.

Yes, this is along the lines of what I think is happening. But if the room credentials expired the recaptcha dialog should appear, if it doesn't then it's likely a bug in the room reconnect logic.

**Comment by PiotrLew** [comment] 2018-12-16 14:04
the problem appears every Friday evening. later it was normal for a month. since yesterday, no room has been standing longer than an hour. How can we fix it? Give you a picture of my console that pops up?

**Comment by basro** [comment] 2018-12-16 14:07
I'm looking into it, for now have patience while I'll figure it out.

**Comment by PiotrLew** [comment] 2018-12-16 15:03
http://prntscr.com/lvne2y 
he does it again. I noticed that it crashes every vps and some ordinary rooms. I hope that this information will help with something

**Comment by PiotrLew** [comment] 2018-12-16 15:31
no, only ,,pub''

**Comment by Gorillaz2-D** [comment] 2018-12-16 15:46
my room is with the same problem, it automatically puts password in the 19/20.

**Comment by Gorillaz2-D** [comment] 2018-12-16 15:51
The problem started yesterday in my room, it has an automatic password when it gets 19/20.

**Comment by jvschiavo** [comment] 2018-12-16 19:34
I also have this problem.

> > Sometimes Haxball goes down and throws Cloudflare errors for a while. Which can cause headless to lose connection (?). Haxball thinks connection closed, token expires. Room can't reappear anymore.
> 
> Yes, this is along the lines of what I think is happening. But if the room credentials expired the recaptcha dialog should appear, if it doesn't then it's likely a bug in the room reconnect logic.

I don't use tokens and the recaptcha dialog doesn't reappear for me.

**Comment by evi1a** [comment] 2018-12-16 19:57
Okay, now one room crashed finally :laughing: and the reCaptcha appeared.

**Comment by basro** [comment] 2018-12-16 20:33
I have now been able to reproduce this bug,  I have some ideas of why it might be happening...

**Comment by basro** [comment] 2018-12-16 22:22
I **believe** I've found the problem, there was a subtle bug in the room list server.  The server has been updated with a fix, the bug should hopefully stop happening now.

No action needs to be taken by the room hosts so there's no need to refresh/restart for the fix to apply to your room.

Since the bug is pretty hard to reproduce I'm not 100% certain that the problem is fixed, so please keep an eye out for it and tell me if it continues to happen. If no one reports any problems for a few days I'll consider it fixed and close this issue.

**Comment by Gorillaz2-D** [comment] 2018-12-16 22:56
Thanks, basro.
My room reappeared, so far no problems.

**Comment by evi1a** [comment] 2018-12-18 00:08
Thank you. So far no crash, I'll post here if it happens again.

**Comment by meisterrr** [comment] 2018-12-18 14:02
Now the other bug, room isn't disappears but its unnable to join to it after certain time, i created new post. #656

**Comment by basro** [comment] 2018-12-18 15:58
I believe the fix worked so I'm closing this issue.

**Closed by basro** 2018-12-18 15:58 UTC
Labels: bug

**Comment by joqnez46** [comment] 2023-10-30 22:44
q

**Comment by joqnez46** [comment] 2023-10-30 22:44
still having the problem

**Comment by np-stacks** [comment] 2024-05-05 16:17
The problem is reappearing
