### ISSUE TITLE
Auto button

### ISSUE THREAD

**Issue by cr0ndor** [haxball/haxball-issues#253] opened 2018-05-01 00:27 UTC
Is there a way we could change this back to the flash version of Auto (i.e., random, not from the top)? I wouldn't mind a Random button be added alongside either.

**Comment by saviola777** [comment] 2018-05-01 06:55
Duplicate of #66.

**Comment by basro** [comment] 2018-05-01 11:13
As I mentioned in #66 I still intend to add the random button.
Closing because duplicate.

**Closed by basro** 2018-05-01 11:13 UTC
Labels: duplicate
