### ISSUE TITLE
Incoherence

### ISSUE THREAD

**Issue by Leo-MapCreator** [haxball/haxball-issues#272] opened 2018-05-15 19:11 UTC
Haxball HTML5 is now official and it doesnt even have '/store' command available. ?????

**Comment by Whunpp2** [comment] 2018-05-16 01:38
Download or Upload them. /store not more necessary than other stuffs.
Also it is in the list for upgrades. #164

**Comment by Leo-MapCreator** [comment] 2018-05-16 01:47
I dont like to upload maps, people download it and change the name of map the to look like that they made the map instead of me, and the upload it again, the person receives all the credits while i receive nothing

**Comment by Leo-MapCreator** [comment] 2018-05-16 01:48
Its not about requesting /store feature, its about the incoherence of publishing a game as official when you dont have some essential features

**Comment by Whunpp2** [comment] 2018-05-16 01:58
I dont know if /store is super essential. For me is not essential. Maybe the "rand" was more than /store. But if is that your opinion, thats ok.

**Comment by Leo-MapCreator** [comment] 2018-05-16 02:09
Some maps doesnt have it's file uploaded on haxmaps, and it only survive trough /store, its the only way to be able to play that kind of map

**Comment by basro** [comment] 2018-05-16 13:04
The reason why the /store command is not yet implemented is that there's stricter limitations in html5 about storing data locally in the user's computers compared to flash.

There's a possible work-around that could be done but it's fairly complex so it'll take some time.

I'm closing this issue because it's a duplicate of #164

**Closed by basro** 2018-05-16 13:04 UTC
Labels: duplicate
