### ISSUE TITLE
Implementing a room view from a “ghost” player perspective.

### ISSUE THREAD

**Issue by haxballer** [haxball/haxball-issues#145] opened 2017-11-10 07:40 UTC
Currently playing streams in HaxBall is very tiring and uninteresting, because the person who streams the given match usually has terrible lag, resulting in low quality streams, as well as making room slots for 4vs4, where the entire stream staff must fit. Is also a problem. What is our solution? It's about being able to create a “ghost” player so that we can peer through the game rooms without going to them, it could not only be useful for streamers, but also for players who want to peek into the room to see if their friends are there. In conclusion, we would like it to be an option for players to be able to retrieve information from a given room as in replays is being made, and then be able to send event events on a link page by retrieving information from the room, so you can avoid physical join to the room. I count on the answer whether such a thing is possible. I would say it would help all “professional” HaxBall players they like to broadcast matches.

**Comment by saviola777** [comment] 2017-11-10 19:57
I believe this is a duplicate of, or at least closely related to, #45?

**Comment by haxballer** [comment] 2017-11-10 20:04
Right, although my idea is more detailed and elaborate, although I have not noticed that topic, for which I apologize.

**Comment by basro** [comment] 2017-11-10 20:08
This kind of thing is not possible to implement, you cannot peek into a room without connecting to it and using the host's bandwidth.

**Closed by basro** 2017-11-10 20:08 UTC

**Comment by haxballer** [comment] 2017-11-11 07:07
My friend, who is also a programmer, suggested me doing this kind of test and claims that it crashes, but that's possible, so I don't know what to think of it. If not, It's too bad.
