### ISSUE TITLE
Delay/movement issue

### ISSUE THREAD

**Issue by CvRkk** [haxball/haxball-issues#329] opened 2018-05-26 10:56 UTC
Hello,

My issue is about having a "delay" in movement in some haxball rooms. To explain it, the gameplay feels different in some rooms and it depends on who hosts the room. I had this issue for a while already and I thought it might be an issue of my computer, but today I tried to play on several public rooms and on some of them the gameplay was "normal" (game reacted instantly) and in some rooms I had this delay and the gameplay felt way different, like every move I did was registered by the game a little bit slower. The same delay I have on my own host that I create, too. So basically in the same moment the gameplay or the game physics feel to be different depending on the host where I play.

All I know is that the problem is not the ping, I have delay on rooms with 30/50/70 ping, as well as my own host, doesnt really matter. No idea where the problem could be thought.

**Comment by basro** [comment] 2018-05-26 16:15
My first thought is that it's a GPU buffering problem. Sometimes instead of displaying immediately GPU drivers will store the drawing commands and show them with delay, I've seen this cause very significant input lag in some games + computer combinations (although never seen it with html5 haxball)

Your claim that in some rooms this would does not happen might be evidence against this, although it could simply be a coincidence that the GPU lag got reduced just as you joined those rooms.

Were you able reliably reproduce the no-input-delay on some rooms? For example: join a room and observe you have no input delay then host a room and observe you do and then rejoin that room and verify that you still have no delay there.

Have you tried with multiple browsers?

Could you tell me browser versions you tried with, your computer's OS, the gpu and cpu model?

**Comment by CvRkk** [comment] 2018-05-26 17:04
> Were you able reliably reproduce the no-input-delay on some rooms? For example: join a room and observe you have no input delay then host a room and observe you do and then rejoin that room and verify that you still have no delay there.

Yes, its same specific rooms where I have no delay and same specific rooms where I do have delay.


> Have you tried with multiple browsers?

I tried latest version of Mozilla, Google Chrome, Maxthon and even custom created HTML Haxball Window, all of them had the same result.


> your computer's OS, the gpu and cpu model?

Windows 10
NVIDIA GeForce GTX 1050Ti
Intel® Core™ i5-650 Processor (4M Cache, 3.20 GHz)


I can mention that it happens on flash version of haxball, too.

**Comment by basro** [comment] 2018-05-26 20:08
The fact that it happens in the flash version too also points towards a GPU delay issue.
Are you 101% sure about it being fixed in some rooms? can you reproduce it again now?
How big would you say the input delay is?

Have you tried updating your GPU drivers?
If you have the nvidia control panel please try changing the "Maximum pre-rendered frames" setting to 1 (Can be found in the Manage 3D settings section)

**Comment by CvRkk** [comment] 2018-05-28 13:55
Looks like it is not fixed in any room at the moment. The delay is not big but its significant enough to not be able to play haxball properly. I experienced also a sound delay. I had my drivers updated, changing maximum pre-rendered frames did not help. I also tried to install older GPU driver but it did not help.

**Comment by basro** [comment] 2018-05-29 14:34
Do you have similar input lag when playing other non-browser games in windowed mode? (Fullscreen might share the same issues.)

HaxBall sounds can be delayed for other reasons (since they are not predicted), they wouldn't be a good indicator of this problem.

**Comment by CvRkk** [comment] 2018-05-29 15:15
> Do you have similar input lag when playing other non-browser games in windowed mode? (Fullscreen might share the same issues.)

Looks like I do, tried it now with TrackMania in windowed and it felt like the game reacted to my commnads slower than usual when I play on fullscreen.

**Comment by basro** [comment] 2018-05-29 15:26
Ok, since it turns out not to be a problem with haxball I'm going to close this issue.

I'm sure there's some way to fix your input lag problem, if I was on your shoes I'd try messing with a lot of settings to see if it fixes. When googling for clues make sure to use windowed and input lag as keywords.

If you do find a way to solve your problem please let me know.

Also, trackmania is a great game 👍

**Comment by basro** [comment] 2018-05-29 15:55
Actually, thinking about it a little bit, there's something I could do to perhaps improve your experience...
I could implement an extraplation setting that tells the game to render with some amount of extra prediction time, this could cancel out the effect of input lag at the cost of seeing yourself warp-around a bit.

**Comment by CvRkk** [comment] 2018-05-29 21:18
I found out my issue is about Windows 10, as this operation system forces vsync, triple buffering and some other stuff when you are not in fullscreen mode. When switched to fullscreen, the game works well, only there is a screen tearing thats really terrible for haxball experience. But yea, this is a Windows 10 issue and I cant really do much about it.

**Comment by basro** [comment] 2018-05-30 20:20
I've added a chat command called `extrapolation`, please try it and see if it makes your input lag feel a bit better.

Example: `/extrapolation 16`

It causes the game to be extrapolated by a certain amount of milliseconds, it will make everything a bit more "warpy" but it could perhaps compensate for your input lag.

**Comment by basro** [comment] 2018-06-05 23:07
@CvRkk have you tried this feature? I'd like to know if it helped your case or not.

**Comment by CvRkk** [comment] 2018-06-06 21:42
I tried, but it doesnt help much the delay that I get because of vsync. My only solution is to play with fullscreen to disable forced vsync on Windows 10.

Anyway few more guys tried it as well and they said the same as Mambajus above, so it definetely helps some people to improve their haxball experience.

**Comment by basro** [comment] 2018-06-07 16:47
Ok, that's unfortunate. At least it's useful for a few people.

**Closed by basro** 2018-06-07 16:47 UTC
Labels: input lag
