### ISSUE TITLE
Breaking change in onPlayerKicked

### ISSUE THREAD

**Issue by NiExTy** [haxball/haxball-issues#827] opened 2019-07-29 20:07 UTC
Breaking change in `onPlayerKicked` which returns `null` in `byPlayer` instead of `PlayerObject` when any admin player kicks out himself. This causes crashes in code that expects `PlayerObject`.

I know that `noPlayer` does that, but I didn't use it.

**Comment by basro** [comment] 2019-07-29 20:17
I'm not able to reproduce this.

**Comment by NiExTy** [comment] 2019-07-29 20:32
Example code:

```
const room = HBInit({
	public: false,
	roomName: 'Test',
	playerName: 'Host',
});

room.onPlayerKicked = function(kickedPlayer, reason, ban, byPlayer) {
	console.log('byPlayer', byPlayer);
}
```
Join room.

`room.setPlayerAdmin(1, true);`

Kick yourself out from the room using UI.

Prints: `byPlayer null`

**Comment by basro** [comment] 2019-07-29 20:36
It only happens if a player kicks himself, I'm not sure that this bug was introduced in the last update. It might have been like this before too.

**Comment by basro** [comment] 2019-07-29 20:43
I've now confirmed that this bug is caused by a change in the last update, I'll be fixing it soon.

Thanks for reporting it.

**Comment by basro** [comment] 2019-07-29 20:59
The bug should be fixed now.

I also noticed I read your message wrong and you had properly explained that it happens when the player kicks himself. Sorry!

**Closed by basro** 2019-07-29 20:59 UTC
Labels: bug
