### ISSUE TITLE
with firefox no more sounds for chat messages and ball kicked action

### ISSUE THREAD

**Issue by ahahahaah** [haxball/haxball-issues#2082] opened 2023-11-01 10:15 UTC
**Since yesterday with firefox:**
 - during a game the crowd sound works but the ball kicked sounds don't
 - on the chat the @user command +message sends a sound but the general chat messages don't

not a problem from my sound card or drivers or something else since some sounds work (crowd and @user messages in chat) **AND** all sounds work with chrome browser but not with firefox since yesterday...

i have tested the safe mode to be sure that it is not an add-on problem, but it doesn't work either.

i wanted to test with a different browser "pale moon" but an haxball message said that the game only supports chrome, opera and firefox..

**Comment by basro** [comment] 2023-11-01 12:41
Yesterday I fixed a [long standing bug](https://github.com/haxball/haxball-issues/issues/1371) that prevented haxball from working on safari browsers.

This fix also included changing some sounds from ogg to wav.

My guess is you are using an extension that modifies the haxball sourcecode and thus you are not running the most up to date game code. If that's the case try running without that extension.

**Comment by ahahahaah** [comment] 2023-11-01 22:08
please can you read my message entierely? i wrote that i have tested the safe mode* to be sure that it is not an add-on problem, but it doesn't work either.

(*the safe mode disables all addons)

so can you restore the sounds like they were please?

**Comment by basro** [comment] 2023-11-01 23:27
You are right that I did not properly read what you said about safe mode.

Regardless, what you are describing is too consistent with what would happen if you were to run old code and I can't think of any other reason for why it would happen.

I've tested on Firefox, Chrome and Safari and sounds are working properly on all of them.

**Comment by ahahahaah** [comment] 2023-11-01 23:54
a thing is sure it is that all worked some days ago and without doing anything the issue appears yesterday,
anyway, maybe it is because i'm using the esr version of firefox (because support of windows 7 is finished with normal firefox).
so i presume i have to accept this.

**Comment by ahahahaah** [comment] 2023-11-02 21:46
but something is not clear
why the crowd sounds and the @user messages in the chat sounds are hearable?
why these sounds exist and not the others?

if there is a difference between them, why not use the format of the crowd and @users sounds? it will allow working sounds for everybody

**Comment by basro** [comment] 2023-11-02 22:20
Those two sounds were not modified, the @user sound was already .wav so I didn't need to modify it. The crowd sound was too large as .wav so I left it as .ogg and doesn't currently work in safari.

It's not a format support issue, the change I did changed some sounds from .ogg to .wav. I'm certain the issue is that you are still running old code, I don't know how that would happen without extensions.

**Comment by basro** [comment] 2023-11-02 23:02
Ok, I owe you an appology. To make sure I downloaded firefox ESR and to my surprise the sounds are indeed not working on it.

I'll try to get them to work.

**Comment by ahahahaah** [comment] 2023-11-02 23:04
thank you sir :D

**Comment by basro** [comment] 2023-11-02 23:43
It's fixed now.

**Closed as completed by basro** 2023-11-02 23:43 UTC
Labels: bug

**Comment by ahahahaah** [comment] 2023-11-02 23:49
yeahhhhh!
dude you're a genius !!
