### ISSUE TITLE
Headless rooms currently bugging

### ISSUE THREAD

**Issue by Wazarr94** [haxball/haxball-issues#694] opened 2019-02-06 20:32 UTC
WebSocket connection to 'wss://p2p2.haxball.com/host?token=thr1.????????????????????????????????????-??????' failed: Error during WebSocket handshake: Unexpected response code: 400

**Comment by basro** [comment] 2019-02-06 21:48
This was caused by server downtime, it should be running fine now.
This issue a duplicate of #693.

**Closed by basro** 2019-02-06 21:48 UTC
Labels: duplicate
