### ISSUE TITLE
Map that breaks the room (unhandled exception)

### ISSUE THREAD

**Issue by alpheratz0** [haxball/haxball-issues#1533] opened 2022-01-07 12:22 UTC
Hi, there's a map when loaded breaks completely the room (freezes) and you cant change the map anymore and makes every client to quit and the host itself to crash, I know that you shouldnt give admin privileges to people you dont trust but people sometimes do.

<details>
<summary>Expand to see map content</summary>
<p>

```json
{
	"name": "rip host",
	"width": 500,
	"height": 300,
	"bg": { "type": "grass" },
	"vertexes": [
		{ "x": -40, "y": 22, "cMask": ["wall"] },
		{ "x": 35, "y": 22, "cMask": ["wall"] },
		{ "x": -70, "y": 65, "cMask": ["red"] },
		{ "x": 70, "y": 65, "cMask": ["red"] },
		{ "x": 70, "y": 170, "cMask": ["red"] },
		{ "x": -70, "y": 170, "cMask": ["red"] },
		{ "x": -68, "y": 68, "cMask": ["red"] },
		{ "x": 68, "y": 68, "cMask": ["red"] },
		{ "x": 68, "y": 168, "cMask": ["red"] },
		{ "x": -68, "y": 168, "cMask": ["red"] },
		{ "x": -66, "y": 70, "cMask": ["red"] },
		{ "x": 66, "y": 70, "cMask": ["red"] },
		{ "x": 66, "y": 166, "cMask": ["red"] },
		{ "x": -66, "y": 166, "cMask": ["red"] },
		{ "x": 0, "y": 145, "cMask": ["red"] },
		{ "x": 0, "y": 100, "cMask": ["red"] },
		{ "x": -15, "y": 115, "cMask": ["red"] },
		{ "x": -15, "y": 145, "cMask": ["red"] },
		{ "x": 15, "y": 145, "cMask": ["red"] },
		{ "x": -210, "y": 102, "cMask": ["red"] },
		{ "x": -70, "y": 102, "cMask": ["red"] },
		{ "x": -70, "y": 170, "cMask": ["red"] },
		{ "x": -210, "y": 170, "cMask": ["red"] },
		{ "x": -208, "y": 105, "cMask": ["red"] },
		{ "x": -72, "y": 105, "cMask": ["red"] },
		{ "x": -72, "y": 168, "cMask": ["red"] },
		{ "x": -208, "y": 168, "cMask": ["red"] },
		{ "x": -206, "y": 107, "cMask": ["red"] },
		{ "x": -74, "y": 107, "cMask": ["red"] },
		{ "x": -74, "y": 166, "cMask": ["red"] },
		{ "x": -206, "y": 166, "cMask": ["red"] },
		{ "x": -145.5, "y": 128, "cMask": ["red"] },
		{ "x": -127.5, "y": 132, "cMask": ["red"] },
		{ "x": -148, "y": 155, "cMask": ["red"] },
		{ "x": -125, "y": 155, "cMask": ["red"] }
	],
	"segments": [
		{
			"v0": 0,
			"v1": 1,
			"curve": 71.0048451488344,
			"curveF": 1.4018229166666665,
			"cMask": ["wall"]
		},
		{ "v0": 2, "v1": 3, "cMask": ["red"] },
		{ "v0": 3, "v1": 4, "cMask": ["red"] },
		{ "v0": 2, "v1": 5, "cMask": ["red"] },
		{ "v0": 5, "v1": 4, "cMask": ["red"] },
		{ "v0": 6, "v1": 7, "cMask": ["red"], "color": "FFFFFF" },
		{ "v0": 7, "v1": 8, "cMask": ["red"], "color": "FFFFFF" },
		{ "v0": 6, "v1": 9, "cMask": ["red"], "color": "FFFFFF" },
		{ "v0": 9, "v1": 8, "cMask": ["red"], "color": "FFFFFF" },
		{ "v0": 10, "v1": 11, "cMask": ["red"] },
		{ "v0": 11, "v1": 12, "cMask": ["red"] },
		{ "v0": 10, "v1": 13, "cMask": ["red"] },
		{ "v0": 13, "v1": 12, "cMask": ["red"] },
		{ "v0": 14, "v1": 15, "cMask": ["red"], "color": "FFFFFF" },
		{ "v0": 16, "v1": 15, "cMask": ["red"], "color": "FFFFFF" },
		{ "v0": 17, "v1": 18, "cMask": ["red"], "color": "FFFFFF" },
		{ "v0": 19, "v1": 20, "cMask": ["red"] },
		{ "v0": 19, "v1": 22, "cMask": ["red"] },
		{ "v0": 22, "v1": 21, "cMask": ["red"] },
		{ "v0": 23, "v1": 24, "cMask": ["red"], "color": "FFFFFF" },
		{ "v0": 23, "v1": 26, "cMask": ["red"], "color": "FFFFFF" },
		{ "v0": 26, "v1": 25, "cMask": ["red"], "color": "FFFFFF" },
		{ "v0": 27, "v1": 28, "cMask": ["red"] },
		{ "v0": 27, "v1": 30, "cMask": ["red"] },
		{ "v0": 30, "v1": 29, "cMask": ["red"] },
		{
			"v0": 31,
			"v1": 32,
			"curve": -159.90130282375026,
			"curveF": -0.17721518987341756,
			"cMask": ["red"],
			"color": "FFFFFF"
		},
		{ "v0": 32, "v1": 33, "cMask": ["red"], "color": "FFFFFF" },
		{ "v0": 33, "v1": 34, "cMask": ["red"], "color": "FFFFFF" }
	],
	"planes": [
		{ "normal": [0, 1], "dist": -294, "bCoef": 0 },
		{ "normal": [0, -1], "dist": -293, "bCoef": 0 },
		{ "normal": [1, 0], "dist": -494, "bCoef": 0 },
		{ "normal": [-1, 0], "dist": -493, "bCoef": 0 }
	],
	"goals": [],
	"discs": [],
	"playerPhysics": {},
	"ballPhysics": "disc0",
	"spawnDistance": 277.5
}
```

</p>
</details>

## Screenshot 
Here is a screenshot of the console after the map is loaded and the `Start Game` button is pressed
\
![console-screenshot](https://user-images.githubusercontent.com/93066036/148543054-2be246f5-da4c-4149-9156-3b6dba87620e.png)

**Comment by thenorthstar** [comment] 2022-01-07 16:37
> Hi, there's a map when loaded breaks completely the room (freezes) and you cant change the map anymore and makes every client to quit and the host itself to crash, I know that you shouldnt give admin privileges to people you dont trust but people sometimes do.
> 
> Expand to see map content
> ## Screenshot
> Here is a screenshot of the console after the map is loaded and the `Start Game` button is pressed ![console-screenshot](https://user-images.githubusercontent.com/93066036/148543054-2be246f5-da4c-4149-9156-3b6dba87620e.png)

@alpheratz0 Duplicate of #1473.

**Comment by alpheratz0** [comment] 2022-01-07 16:59
@thenorthstar oh I didn't notice, anyway basro didn't fix it and your solution doesnt prevent the 'bug' from happening. It would be better if haxball detects the map as invalid.

**Comment by Wazarr94** [comment] 2022-01-08 13:34
The problem is setting ballPhysics to disc0 with no discs. Here's what's said about that in the wiki:
`Setting ballPhysics to the string "disc0" will instead use the first disc as the ball.`

Apparently, there's no check about having no discs with the disc0 setting, it should take one line to correct.

**Comment by thenorthstar** [comment] 2022-01-08 20:10
> @thenorthstar oh I didn't notice, anyway basro didn't fix it and your solution doesnt prevent the 'bug' from happening. It would be better if haxball detects the map as invalid.

@alpheratz0 Already I had shared a temporary solution, this job is up to @basro.

**Comment by basro** [comment] 2023-04-29 00:18
This is now fixed in the latest headless.js

**Closed as completed by basro** 2023-04-29 00:18 UTC
Labels: bug
